name: Publish

on:
  release:
    types: [ created ]

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - run: npm install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
