name: Publish

on:
  pull_request:
    branches:
      - master
    types: 
      - closed

jobs:

  # Build the project
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/v')

    steps:
      - uses: actions/checkout@v2
        with:
          token: '${{ secrets.REPO_TOKEN }}'
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm ci
      - run: npm run build
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: publish-${{ github.sha }}

  # Tag master
  tag:
    name: Tag master
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: publish-${{ github.sha }}
      - run: echo ${{ github.event.pull_request.head.ref }} | perl -nle 'm/release\/(v\d+\.\d+\.\d+)/; print "VERSION=$1"' >> $GITHUB_ENV
      - run: git config --global user.name 'VuziBot'
      - run: git config --global user.email 'vuzi@protonmail.com'
      - run: git tag -a ${{ env.VERSION }} -m "Release ${{ env.VERSION }}"
      - run: git push origin ${{ env.VERSION }}
      - run: echo "::set-output name=version::${{ env.VERSION }}"

  # Perform a release
  release:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: publish-${{ github.sha }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ steps.tag.outputs.version }}
          files: |
            LICENSE.md

  # Publish to NPM
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: publish-${{ github.sha }}
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          
