name: Release

on:
  pull_request:
    types: [closed]

jobs:
  # Setup job, get nodeJs and checkout
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

  # Check that the project build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm ci
      - run: npm run build

  # Tag master
  tag:
    name: Tag master
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm ci
      - run: npm run build

  # Perform a release
  release:
    name: Release to Github
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: false
          files: |
            LICENSE.md

  # Publish to NPM
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
