name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true

jobs:
  # Setup job, get nodeJs and checkout
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

  # Check that the project build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm ci
      - run: npm run build

  # Check that all the tests pass
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm start -- run example out
      - run: npm test

  # Bump the package.json version
  bump:
    name: Bump package.json to ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    needs: test

    steps:
      - run: npm version ${{ github.event.inputs.version }}
      - uses: EndBug/add-and-commit@v7
        with:
          add: package.json
          tag: '${{ github.event.inputs.version }} --force'
          message: Release ${{ github.event.inputs.version }}

  # Perform a release
  release:
    name: Release ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md

  # Publish to NPM
  publish:
    name: Publish on NPM
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
