name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true

jobs:
  # Setup job, get nodeJs and checkout
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

  # Check that the project build
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm ci
      - run: npm run build

  # Check that all the tests pass
  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm start -- run example out
      - run: npm test

  # Bump the package.json version
  bump:
    name: Bump package.json
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: |
          git config --global user.email "github-action@users.noreply.github.com"
          git config --global user.name "GitHub Action"
      - uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "release-v${{ github.event.inputs.version }}"
      - run: npm version --no-git-tag-version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
      - uses: repo-sync/pull-request@v2
        with:
          source_branch: "release-v${{ github.event.inputs.version }}"  
          destination_branch: master
          pr_title: "Release ${{ github.event.inputs.version }}"
          pr_body: "Release to version ${{ github.event.inputs.version }}"
          pr_label: "release"
          github_token: ${{ secrets.GITHUB_TOKEN }}
