name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm ci
      - run: npm run build
      - run: npm run build

  test:
    name: Tests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - run: npm start -- run example out
      - run: npm test

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.md
