name: Release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true

jobs:

  # Build the project
  build:
    name: Build
    description: Setup the environement & build the project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the project on master
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
      - name: Install nodeJs
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install & build the project
        run: | 
          npm ci
          npm run build
      - name: Create the cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: release-${{ github.sha }}

  # Check that all the tests pass
  test:
    name: Tests
    description: Check that all the tests pass
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: release-${{ github.sha }}
      - name: Run the app
        run: npm start -- run example out
      - name: Run the tests
        run: npm test

  # Bump the package.json version, create a commit and tag the commit
  bump:
    name: Bump package.json
    description: Bump the package.json version, create a commit and tag the commit, and push the result on master
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: release-${{ github.sha }}
      - name: Configure git user
        run: |
          git config --global user.name 'VuziBot'
          git config --global user.email 'vuzi@protonmail.com'
      - name: Bump NPM version
        run: npm version --no-git-tag-version ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
      - name: Create a bump commit & tag
        run: |
          git commit -m "Bump version to ${{ github.event.inputs.version }}" -a
          git tag -a ${{ github.event.inputs.version }} -m "Release ${{ github.event.inputs.version }}"
      - name: Push the changes
        run: git push --follow-tags

  # Perform a release
  release:
    name: Release to Github
    description: Perform a release to Github
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: release-${{ github.sha }}
      - name: Create the Github release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.REPO_TOKEN }}
          prerelease: false
          automatic_release_tag: ${{ github.event.inputs.version }}
          files: |
            LICENSE.md

  # Publishes to NPM
  publish:
    name: Publishes to NPM
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - name: Restore cache
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: release-${{ github.sha }}
      - name: Publish the NPM release
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

