name: Dump

on:
  pull_request:
    types: [closed]

jobs:
  # Setup job, get nodeJs and checkout
  dump:
    name: Dump GitHub context
    runs-on: ubuntu-latest
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}

    steps:
      - run: |
          echo "$GITHUB_CONTEXT"
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.head.ref }}

